<a href="https://colab.research.google.com/github/vfunnny2000/NN/blob/main/HW_5/Lesson_5_NN_HW_1_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import re

In [2]:
with open('/content/train_data.txt', 'r', encoding='utf-8') as f:
    text = f.read()
    text = text.replace('\ufeff', '') # убираем первый невидимый символ
    text = re.sub(r'[^А-я ]', '', text) # убираем все недопустимые символы

In [3]:
text

'Немного про нейронные сетиНейронные сети  это алгоритмы машинного обучения вдохновленные структурой и функционированием человеческого мозга Они состоят из узлов нейронов соединенных слоями которые могут обучаться на определенных данных для выполнения разнообразных задач включая обработку естественного языка В контексте  нейронные сети используются для интерпретации анализа и генерации текстовых данных Они способны улавливать контекст семантику и нюансы языка что делает их идеальными для задач таких как перевод классификация текста анализ настроений и автоматическое резюмирование'

In [4]:
num_characters = 34
#33 буквы + пробел

In [5]:
import keras
from keras.preprocessing.text import Tokenizer

In [6]:
tokenizer = Tokenizer(num_words=num_characters, char_level=True)

In [7]:
tokenizer.fit_on_texts(text)

In [8]:
print(tokenizer.word_index)

{' ': 1, 'н': 2, 'о': 3, 'е': 4, 'и': 5, 'а': 6, 'т': 7, 'с': 8, 'р': 9, 'к': 10, 'л': 11, 'ы': 12, 'в': 13, 'я': 14, 'д': 15, 'з': 16, 'м': 17, 'у': 18, 'ч': 19, 'х': 20, 'г': 21, 'п': 22, 'й': 23, 'б': 24, 'ц': 25, 'ь': 26, 'ю': 27, 'ф': 28, 'э': 29, 'ш': 30}


In [9]:
inp_chars = 6 #
data = tokenizer.texts_to_matrix(text)

In [10]:
data[1]

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
n = data.shape[0]-inp_chars
n  #размер обучающего множества

579

In [12]:
import numpy as np

In [13]:
X = np.array([data[i:i+inp_chars, :] for i in range(n)])
Y = data[inp_chars:] #предсказание следующего символа

In [14]:
len(X)

579

In [15]:
X[0]

array([[0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.]])

In [16]:
Y[0]

array([0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [17]:
from keras.layers import *
from keras.models import Sequential

In [18]:
model = Sequential()
model.add(Input((inp_chars, num_characters)))
model.add(SimpleRNN(500, activation='tanh'))
model.add(Dense(num_characters, activation='softmax'))
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn (SimpleRNN)      (None, 500)               267500    
                                                                 
 dense (Dense)               (None, 34)                17034     
                                                                 
Total params: 284534 (1.09 MB)
Trainable params: 284534 (1.09 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [19]:
model.compile(loss='categorical_crossentropy', metrics=['accuracy'], optimizer='adam')
history = model.fit(X, Y, batch_size=32, epochs=100)

Epoch 1/100
19/19 [==============================] - 2s 17ms/step - loss: 3.2021 - accuracy: 0.1209
Epoch 2/100
19/19 [==============================] - 0s 17ms/step - loss: 2.5594 - accuracy: 0.2729
Epoch 3/100
19/19 [==============================] - 0s 16ms/step - loss: 2.2895 - accuracy: 0.3057
Epoch 4/100
19/19 [==============================] - 0s 16ms/step - loss: 2.0410 - accuracy: 0.3679
Epoch 5/100
19/19 [==============================] - 0s 17ms/step - loss: 1.9088 - accuracy: 0.3921
Epoch 6/100
19/19 [==============================] - 1s 27ms/step - loss: 1.7939 - accuracy: 0.4439
Epoch 7/100
19/19 [==============================] - 1s 27ms/step - loss: 1.7351 - accuracy: 0.4646
Epoch 8/100
19/19 [==============================] - 0s 23ms/step - loss: 1.7614 - accuracy: 0.4629
Epoch 9/100
19/19 [==============================] - 1s 26ms/step - loss: 1.6472 - accuracy: 0.5060
Epoch 10/100
19/19 [==============================] - 0s 26ms/step - loss: 1.6052 - accuracy: 0.4888

In [20]:
def buildPhrase(inp_str, str_len = 50):
  for i in range(str_len):
    x = []
    for j in range(i, i+inp_chars):
      x.append(tokenizer.texts_to_matrix(inp_str[j])) # преобразуем символы в One-Hot-encoding

    x = np.array(x)
    inp = x.reshape(1, inp_chars, num_characters)

    pred = model.predict( inp ) # предсказываем OHE четвертого символа
    d = tokenizer.index_word[pred.argmax(axis=1)[0]] # получаем ответ в символьном представлении

    inp_str += d # дописываем строку

  return inp_str

In [21]:
res = buildPhrase("немног")
print(res)

1/1 [==============================] - 0s 24ms/step
немного про нейронные сети  спольбуютсяядля интерпретаци


In [22]:
with open('/content/train_data.txt', 'r', encoding='utf-8') as f:
    texts = f.read()
    texts = texts.replace('\ufeff', '') # убираем первый невидимый символ

In [23]:
maxWordsCount = 1000
tokenizer = Tokenizer(num_words=maxWordsCount, filters='!–"—#$%&amp;()*+,-./:;<=>?@[\\]^_`{|}~\t\n\r«»',
                       lower=True, split=' ', char_level=False)
tokenizer.fit_on_texts([texts])

In [24]:
dist = list(tokenizer.word_counts.items())
print(dist[:10])

[('немного', 1), ('про', 1), ('нейронные', 3), ('сети', 3), ('это', 1), ('алгоритмы', 1), ('машинного', 1), ('обучения', 1), ('вдохновленные', 1), ('структурой', 1)]


In [25]:
data = tokenizer.texts_to_sequences([texts])


In [26]:
data

[[10,
  11,
  2,
  3,
  2,
  3,
  12,
  13,
  14,
  15,
  16,
  17,
  1,
  18,
  19,
  20,
  5,
  21,
  22,
  23,
  24,
  25,
  26,
  27,
  28,
  29,
  30,
  31,
  6,
  4,
  32,
  33,
  7,
  34,
  35,
  36,
  8,
  9,
  37,
  38,
  9,
  2,
  3,
  39,
  4,
  40,
  41,
  1,
  42,
  43,
  6,
  5,
  44,
  45,
  46,
  47,
  1,
  48,
  8,
  49,
  50,
  51,
  52,
  4,
  7,
  53,
  54,
  55,
  56,
  57,
  58,
  59,
  1,
  60,
  61]]

In [27]:
len(data[0])

75

In [28]:
res = keras.utils.to_categorical(data[0], num_classes=maxWordsCount)
print( res.shape )

(75, 1000)


In [29]:
inp_words = 3
n = res.shape[0]-inp_words

In [30]:
X = np.array([res[i:i+inp_words, :] for i in range(n)])
Y = res[inp_words:]

In [31]:
from keras.layers import *
from keras.models import Sequential

In [32]:
model = Sequential()
model.add(Input((inp_words, maxWordsCount)))
model.add(SimpleRNN(128, activation='tanh'))
model.add(Dense(maxWordsCount, activation='softmax'))
model.summary()

model.compile(loss='categorical_crossentropy', metrics=['accuracy'], optimizer='adam')

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn_1 (SimpleRNN)    (None, 128)               144512    
                                                                 
 dense_1 (Dense)             (None, 1000)              129000    
                                                                 
Total params: 273512 (1.04 MB)
Trainable params: 273512 (1.04 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [35]:
history = model.fit(X, Y, batch_size=32, epochs=20)

Epoch 1/20
3/3 [==============================] - 0s 17ms/step - loss: 3.4333 - accuracy: 0.1528
Epoch 2/20
3/3 [==============================] - 0s 17ms/step - loss: 3.3765 - accuracy: 0.1944
Epoch 3/20
3/3 [==============================] - 0s 17ms/step - loss: 3.3212 - accuracy: 0.2222
Epoch 4/20
3/3 [==============================] - 0s 18ms/step - loss: 3.2625 - accuracy: 0.2500
Epoch 5/20
3/3 [==============================] - 0s 19ms/step - loss: 3.1982 - accuracy: 0.3056
Epoch 6/20
3/3 [==============================] - 0s 15ms/step - loss: 3.1280 - accuracy: 0.3194
Epoch 7/20
3/3 [==============================] - 0s 17ms/step - loss: 3.0538 - accuracy: 0.3750
Epoch 8/20
3/3 [==============================] - 0s 15ms/step - loss: 2.9736 - accuracy: 0.4028
Epoch 9/20
3/3 [==============================] - 0s 14ms/step - loss: 2.8892 - accuracy: 0.5000
Epoch 10/20
3/3 [==============================] - 0s 15ms/step - loss: 2.7999 - accuracy: 0.5417
Epoch 11/20
3/3 [============

In [36]:
def buildPhrase(texts, str_len = 20):
  res = texts
  data = tokenizer.texts_to_sequences([texts])[0]
  for i in range(str_len):
    x = keras.utils.to_categorical(data[i: i+inp_words], num_classes=maxWordsCount) # преобразуем в One-Hot-encoding
    inp = x.reshape(1, inp_words, maxWordsCount)

    pred = model.predict(inp) # предсказываем OHE четвертого символа
    indx = pred.argmax(axis=1)[0]
    data.append(indx)

    res += " " + tokenizer.index_word[indx] # дописываем строку

  return res

In [38]:
res = buildPhrase("нейронные сети используются")
print(res)

1/1 [==============================] - 0s 21ms/step
нейронные сети используются для интерпретации анализа и генерации текстовых данных они способны улавливать контекст семантику и нюансы языка данных делает их разнообразных для


In [ ]:
# x.shape